version: '3.8'
services:
  app:
    image: ready-hire-api:latest
    container_name: ready-hire-api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION_SECONDS=${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS}
      - JWT_REFRESH_TOKEN_EXPIRATION_SECONDS=${JWT_REFRESH_TOKEN_EXPIRATION_SECONDS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH2_REDIRECT_URI=${OAUTH2_REDIRECT_URI}
      - PORTONE_V2_API_SECRET=${PORTONE_V2_API_SECRET}
      - PORTONE_CHANNEL_KEY=${PORTONE_CHANNEL_KEY}
    restart: unless-stopped
