app:
  swagger:
    enabled: false
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://ready-hire-vert.vercel.app}
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI:https://ready-hire-vert.vercel.app/oauth2/callback}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.hibernate.SQL: warn
